// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.5
// source: Msg.proto

package msg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ModuleId int32

const (
	ModuleId_InvalidModuleId ModuleId = 0
	ModuleId_Base            ModuleId = 1
	ModuleId_Player          ModuleId = 2
	ModuleId_Scene           ModuleId = 3
	ModuleId_Notify          ModuleId = 4
	ModuleId_Shops           ModuleId = 5
)

// Enum value maps for ModuleId.
var (
	ModuleId_name = map[int32]string{
		0: "InvalidModuleId",
		1: "Base",
		2: "Player",
		3: "Scene",
		4: "Notify",
		5: "Shops",
	}
	ModuleId_value = map[string]int32{
		"InvalidModuleId": 0,
		"Base":            1,
		"Player":          2,
		"Scene":           3,
		"Notify":          4,
		"Shops":           5,
	}
)

func (x ModuleId) Enum() *ModuleId {
	p := new(ModuleId)
	*p = x
	return p
}

func (x ModuleId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ModuleId) Descriptor() protoreflect.EnumDescriptor {
	return file_Msg_proto_enumTypes[0].Descriptor()
}

func (ModuleId) Type() protoreflect.EnumType {
	return &file_Msg_proto_enumTypes[0]
}

func (x ModuleId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ModuleId.Descriptor instead.
func (ModuleId) EnumDescriptor() ([]byte, []int) {
	return file_Msg_proto_rawDescGZIP(), []int{0}
}

type GameMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ModId int32    `protobuf:"varint,1,opt,name=modId,proto3" json:"modId,omitempty"` //功能模块儿id，主要用来区分消息由哪个系统接收,取值参见ModuleId
	MsgId int32    `protobuf:"varint,2,opt,name=msgId,proto3" json:"msgId,omitempty"` //消息id，一般用于client和game server交互
	Data  []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`    //具体消息内容，为protobuf消息序列化后的内容
	Time  *SvrTime `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`    //服务时间信息
}

func (x *GameMsg) Reset() {
	*x = GameMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameMsg) ProtoMessage() {}

func (x *GameMsg) ProtoReflect() protoreflect.Message {
	mi := &file_Msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameMsg.ProtoReflect.Descriptor instead.
func (*GameMsg) Descriptor() ([]byte, []int) {
	return file_Msg_proto_rawDescGZIP(), []int{0}
}

func (x *GameMsg) GetModId() int32 {
	if x != nil {
		return x.ModId
	}
	return 0
}

func (x *GameMsg) GetMsgId() int32 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *GameMsg) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GameMsg) GetTime() *SvrTime {
	if x != nil {
		return x.Time
	}
	return nil
}

type SvrTime struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp int64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"` //时间戳，单位毫秒，自1970年1月1日开始，根据服务本地时间，可能出现回退
	Monotonic int64 `protobuf:"varint,2,opt,name=monotonic,proto3" json:"monotonic,omitempty"` //自服务启动经过的时间，单位毫秒，保证单调递增
}

func (x *SvrTime) Reset() {
	*x = SvrTime{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Msg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SvrTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SvrTime) ProtoMessage() {}

func (x *SvrTime) ProtoReflect() protoreflect.Message {
	mi := &file_Msg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SvrTime.ProtoReflect.Descriptor instead.
func (*SvrTime) Descriptor() ([]byte, []int) {
	return file_Msg_proto_rawDescGZIP(), []int{1}
}

func (x *SvrTime) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SvrTime) GetMonotonic() int64 {
	if x != nil {
		return x.Monotonic
	}
	return 0
}

var File_Msg_proto protoreflect.FileDescriptor

var file_Msg_proto_rawDesc = []byte{
	0x0a, 0x09, 0x4d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6d, 0x73, 0x67,
	0x22, 0x6b, 0x0a, 0x07, 0x47, 0x61, 0x6d, 0x65, 0x4d, 0x73, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x6d,
	0x6f, 0x64, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x49,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x20, 0x0a, 0x04, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6d, 0x73, 0x67, 0x2e,
	0x53, 0x76, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x45, 0x0a,
	0x07, 0x53, 0x76, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x6f, 0x6e, 0x6f, 0x74, 0x6f,
	0x6e, 0x69, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x6d, 0x6f, 0x6e, 0x6f, 0x74,
	0x6f, 0x6e, 0x69, 0x63, 0x2a, 0x57, 0x0a, 0x08, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x49, 0x64,
	0x12, 0x13, 0x0a, 0x0f, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x4d, 0x6f, 0x64, 0x75, 0x6c,
	0x65, 0x49, 0x64, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x42, 0x61, 0x73, 0x65, 0x10, 0x01, 0x12,
	0x0a, 0x0a, 0x06, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x53,
	0x63, 0x65, 0x6e, 0x65, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79,
	0x10, 0x04, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x68, 0x6f, 0x70, 0x73, 0x10, 0x05, 0x42, 0x0c, 0x5a,
	0x0a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6d, 0x73, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_Msg_proto_rawDescOnce sync.Once
	file_Msg_proto_rawDescData = file_Msg_proto_rawDesc
)

func file_Msg_proto_rawDescGZIP() []byte {
	file_Msg_proto_rawDescOnce.Do(func() {
		file_Msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_Msg_proto_rawDescData)
	})
	return file_Msg_proto_rawDescData
}

var file_Msg_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_Msg_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_Msg_proto_goTypes = []interface{}{
	(ModuleId)(0),   // 0: msg.ModuleId
	(*GameMsg)(nil), // 1: msg.GameMsg
	(*SvrTime)(nil), // 2: msg.SvrTime
}
var file_Msg_proto_depIdxs = []int32{
	2, // 0: msg.GameMsg.time:type_name -> msg.SvrTime
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_Msg_proto_init() }
func file_Msg_proto_init() {
	if File_Msg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Msg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Msg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SvrTime); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Msg_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Msg_proto_goTypes,
		DependencyIndexes: file_Msg_proto_depIdxs,
		EnumInfos:         file_Msg_proto_enumTypes,
		MessageInfos:      file_Msg_proto_msgTypes,
	}.Build()
	File_Msg_proto = out.File
	file_Msg_proto_rawDesc = nil
	file_Msg_proto_goTypes = nil
	file_Msg_proto_depIdxs = nil
}
